/*opere*/

export { default as pref_c } from './pref'
export { default as pref_s } from './prefs'
export { default as directus_users } from './directus_users'
export { default as directus_roles } from './directus_roles'
export { default as regioni } from './regioni'
export { default as Autore } from './autore'
export { default as cmpn } from './cmpn'
export { default as collezione_carte } from './collezione'
export { default as carte_storiche } from './carte_storiche'
export { default as archivi } from './collocazione'
export { default as dtzg } from './dtzg'
export { default as dtzg_carte } from './dtzg'
export { default as dtzs } from './dtzs'
export { default as dtzs_carte } from './dtzs'
export { default as editore_carte } from './editore'
export { default as lingua_carte } from './lingua'
export { default as MTCM } from './mtcm'
export { default as MTCT } from './mtct'
export { default as ogtt } from './ogtt'
export { default as cdgg } from './cdgg'
export { default as serie_italiana } from './serie_italiana'

