/*opere*/
export { default as Foto } from './Foto'
export { default as biblioteca } from './biblioteca'
export { default as bib_autore } from './bib_autore'
export { default as bib_curatore } from './bib_curatore'
export { default as bib_collocazione } from './bib_collocazione'
export { default as bib_armadio } from './bib_armadio'
export { default as bib_utente } from './bib_utente'
export { default as pref_b } from './pref_b'
export { default as directus_users } from './directus_users'
export { default as directus_roles } from './directus_roles'
export { default as bib_editore } from './bib_editore'
export { default as bib_luogo } from './bib_luogo'
export { default as bib_prestito } from './bib_prestito'
export { default as prestiti } from './prestiti'

